version: 2.1
orbs:
  node: circleci/node@1.1.6
  jobs:
      build:
    working_directory: ~/repo
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting